# Generated by Django 4.2.20 on 2025-04-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usercard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercard',
            old_name='univeristy',
            new_name='university',
        ),
    ]
