# Generated by Django 4.2.20 on 2025-05-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_univeristy_usercard_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='username',
            field=models.CharField(default='temp_username', max_length=100, unique=True),
        ),
    ]
