# Generated by Django 4.2.20 on 2025-05-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_itempost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='itempost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
